version: '3.8'

services:
  db:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-network
    volumes:
      - data:/data/db
    entrypoint: ['/usr/bin/mongod', '--replSet', 'rs0', '--bind_ip_all']

  initializer:
    image: mongo:4.4
    depends_on:
      - db
    networks:
      - mongo-network
    command:
      - /bin/sh
      - -c
      - |
        sleep 2 && 
        mongo --host db:27017 --eval "
        if (!rs.status().ok) {
          rs.initiate();
        }

        db = (new Mongo('db:27017')).getDB('local');

        if (db.oplog.rs.stats().maxSize.toNumber() !== 2097152000) {
          db.adminCommand({ 'replSetResizeOplog': 1, 'size': 2000 });
          db.runCommand({ 'compact': 'oplog.rs', 'force': true });
        }
        "

networks:
  mongo-network:
    driver: bridge

volumes:
  data:
