version: '3.8'

services:
  db:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-network
    volumes:
      - data:/data/db
    entrypoint: ['/usr/bin/mongod', '--replSet', 'rs0', '--bind_ip_all']

  initializer:
    image: mongo:4.4
    networks:
      - mongo-network
    command: /bin/sh -c "sleep 2 && mongo --host db:27017 --eval \"rs.initiate()\""

networks:
  mongo-network:
    driver: bridge

volumes:
  data:
