version: '3'

services:
  db1:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - private_network
      - public_network
    volumes:
      - db1_data:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017' ]

  db2:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27018:27018'
    networks:
      - private_network
      - public_network
    volumes:
      - db2_data:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27018' ]

  db3:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27019:27019'
    networks:
      - private_network
      - public_network
    volumes:
      - db3_data:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27019' ]

  initializer:
    image: mongo:latest
    depends_on:
      - db1
      - db2
      - db3
    networks:
      - private_network
    command:
      - /bin/sh
      - -c
      - |
        sleep 2 && mongosh --host db1:27017 --eval '
          rs.initiate({
            _id: "rs0",
            version: 1,
            members: [
              {
                _id: 0,
                host: "db1:27017",
                priority: 3
              },
              {
                _id: 1,
                host: "db2:27018",
                priority: 2
              },
              {
                _id: 2,
                host: "db3:27019",
                priority: 1
              }
            ]
          });
        
          rs.status();
        '

networks:
  private_network:
  public_network:
    driver: bridge

volumes:
  db1_data:
  db2_data:
  db3_data:
